#-------------------------------
# Site Settings
title: Jube
logo: '/images/logo.png'
description: Jube is open-source transaction and event monitoring software.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Services'
      submenu:
        - url: '/training'
          title: 'Training'
        - url: '/support'
          title: 'Lean Support'
    - title: 'Learn'
      submenu:
        - title: 'Docs'
          url: 'https://jube-home.github.io/jube/'
        - title: 'Sandbox'
          url: 'https://sandbox.jube.io/'
        - title: 'GitHub'
          url: 'https://github.com/jube-home/jube'
    - title: 'Contact'
      url: '/contact'

#-------------------------------
# Hero Settings
hero:
  hero__title: Open-Source Transaction and Event Monitoring Software
  hero__description: Jube is an open-source software designed for monitoring transactions and events. It offers a range of powerful features including real-time data wrangling, artificial intelligence, decision making, and case management. Jube's exceptional performance is particularly evident in its application to fraud prevention and abuse detection scenarios.
  hero__image: '/images/Jube.png'

#-------------------------------
# Google Analytics
google-analytics: G-7PYZ045CND
